package app.core.engines.user_profile

import android.content.Context.*
import app.core.*
import app.core.AIOApp.Companion.INSTANCE
import app.core.AIOApp.Companion.aioDSLJsonInstance
import app.core.AIOApp.Companion.aioUserProfile
import app.core.engines.fst_serializer.FSTBuilder.fstConfig
import com.anggrayudi.storage.file.*
import com.dslplatform.json.*
import io.objectbox.annotation.*
import lib.files.FileSystemUtility.readStringFromInternalStorage
import lib.files.FileSystemUtility.saveStringToInternalStorage
import lib.process.*
import java.io.*
import kotlin.jvm.Transient

/**
 * Represents a user's profile data within the application.
 *
 * This class is designed to be a central repository for user-specific information,
 * such as authentication status and personal details. It supports multiple persistence
 * mechanisms to ensure data integrity and backward compatibility.
 *
 * The data is persisted in three ways:
 * 1.  **ObjectBox Database:** As an `@Entity`, it is stored in a structured, efficient database.
 * 2.  **JSON File:** A human-readable JSON representation (`user_profile.json`) is saved
 *     in the app's internal storage for easy debugging and potential cross-platform use.
 * 3.  **Binary File:** A serialized binary format (`user_profile.dat`) is used for fast
 *     read/write operations, leveraging FST serialization.
 *
 * The class includes logic to read from older formats (binary, then JSON) and migrate
 * the data to the current persistence layers upon initialization.
 *
 * @property id The unique identifier for the user profile entry in the local ObjectBox database.
 * @property uniqueUserServerId A unique ID assigned by the server to identify the user across devices.
 *           Null if not available.
 * @property isUserCurrentlyLoggedIn A flag indicating whether the user is currently signed into their account.
 * @property userFullName The full name of the user. Null if not provided.
 * @property userEmailAddress The email address associated with the user's account. Null if not provided.
 * @property userPhoneNumber The phone number associated with the user's account. Null if not provided.
 */
@CompiledJson
@Entity
class AIOUserProfile : Serializable {
	
	/**
	 * Logger instance for this class. Marked as `@Transient` to exclude it from serialization.
	 */
	@Transient
	private val logger = LogHelperUtils.from(javaClass)
	
	/**
	 * The unique identifier for this user profile entry in the local ObjectBox database.
	 *
	 * This ID is automatically generated by ObjectBox when the profile is first saved
	 * and serves as the primary key for database operations. It is not intended for use
	 * as a server-side identifier.
	 */
	@Id
	@JvmField
	@JsonAttribute(name = "id")
	var id: Long = 0L
	
	/**
	 * A unique identifier assigned by the server to this user.
	 *
	 * This ID is used to consistently identify the user across different devices or sessions.
	 * It remains `null` if the user has not logged in or if the ID has not yet been
	 * retrieved from the server.
	 */
	@JvmField
	@JsonAttribute(name = "uniqueUserServerId")
	var uniqueUserServerId: String? = null
	
	/**
	 * A flag indicating the user's current authentication status.
	 *
	 * This property is `true` if the user is successfully signed into their account,
	 * and `false` otherwise. It serves as a quick check for login state across the application.
	 * Defaults to `false`.
	 */
	@JvmField
	@JsonAttribute(name = "isUserCurrentlyLoggedIn")
	var isUserCurrentlyLoggedIn: Boolean = false
	
	/**
	 * The full name of the user, as provided during registration or profile updates.
	 * This value is `null` if the user has not provided their full name.
	 */
	@JvmField
	@JsonAttribute(name = "userFullName")
	var userFullName: String? = null
	
	/**
	 * The email address associated with the user's account.
	 * This value is populated during the login or registration process.
	 * It is `null` if the user is not logged in or has not provided an email.
	 */
	@JvmField
	@JsonAttribute(name = "userEmailAddress")
	var userEmailAddress: String? = null
	
	/**
	 * The phone number associated with the user's account, including the country code.
	 * This property is nullable, indicating that the user may not have provided a phone number.
	 * Example: `+11234567890`.
	 */
	@JvmField
	@JsonAttribute(name = "userPhoneNumber")
	var userPhoneNumber: String? = null
	
	/**
	 * Asynchronously reads the user profile from legacy storage formats.
	 *
	 * This function initiates a background process to load the user profile from older
	 * persistence layers, ensuring backward compatibility. It first attempts to load from a
	 * binary file (`user_profile.dat`), and if that fails or the file doesn't exist, it falls
	 * back to a JSON file (`user_profile.json`).
	 *
	 * The operation is performed on a background thread with a timeout to prevent blocking
	 * the main thread. If a profile is successfully loaded, it is migrated to the current
	 * persistence layers (ObjectBox, updated JSON/binary files).
	 *
	 * @see initializeLegacyDataParser
	 */
	fun readObjectFromStorage() {
		ThreadsUtility.executeInBackground(
			timeOutInMilli = 1200,
			codeBlock = {
				initializeLegacyDataParser()
			})
	}
	
	/**
	 * Initializes the user profile by attempting to load data from legacy storage formats.
	 *
	 * This function serves as a migration path for user data stored in older versions of the app.
	 * It follows a specific priority order for loading:
	 * 1.  **Binary File (`user_profile.dat`):** It first tries to load the user profile from a
	 *     fast, FST-serialized binary file. If successful, it populates the `aioUserProfile`
	 *     instance and triggers an update to persist the data in the current storage formats
	 *     (ObjectBox, JSON).
	 * 2.  **JSON File (`user_profile.json`):** If the binary file is not found or fails to load,
	 *     it falls back to reading a human-readable JSON file. If this is successful, the data
	 *     is loaded and similarly persisted to modern storage layers.
	 *
	 * If neither legacy file exists or can be parsed, the function completes without loading
	 * any data, and the application will proceed with a default or new user profile. All
	 * potential errors during file I/O or parsing are caught and logged to prevent crashes.
	 */
	private fun initializeLegacyDataParser() {
		try {
			var isBinaryFileValid = false
			val internalDir = AIOApp.internalDataFolder
			val userProfileBinaryDataFile = internalDir.findFile(USER_PROFILE_FILE_NAME_BINARY)
			if (userProfileBinaryDataFile != null && userProfileBinaryDataFile.exists()) {
				logger.d("Found binary user profile file, attempting to load")
				val absolutePath = userProfileBinaryDataFile.getAbsolutePath(INSTANCE)
				val objectInMemory = loadFromBinary(File(absolutePath))
				
				if (objectInMemory != null) {
					logger.d("Successfully loaded user profile from binary format")
					aioUserProfile = objectInMemory
					aioUserProfile.updateInStorage()
					isBinaryFileValid = true
				} else {
					logger.d("Failed to load user profile from binary format")
				}
			}
			
			if (!isBinaryFileValid) {
				logger.d("Attempting to load user profile from JSON format")
				
				readStringFromInternalStorage(USER_PROFILE_FILE_NAME_JSON).let { jsonString ->
					if (jsonString.isNotEmpty()) {
						convertJSONStringToClass(jsonString = jsonString).let {
							logger.d("Successfully loaded user profile from JSON format")
							aioUserProfile = it
							aioUserProfile.updateInStorage()
						}
					} else {
						logger.d("No JSON user profile found or file empty")
					}
				}
			}
			
		} catch (error: Exception) {
			logger.e("Error reading user profile from storage: ${error.message}", error)
		}
	}
	
	/**
	 * Asynchronously persists the current state of the user profile to all configured storage layers.
	 *
	 * This function orchestrates the saving of the user profile to multiple destinations to ensure
	 * data integrity, redundancy, and backward compatibility. The destinations are:
	 * 1.  **ObjectBox Database:** The profile is saved as an entity, which is the primary and most
	 *     efficient persistence mechanism.
	 * 2.  **JSON File:** A human-readable JSON representation (`user_profile.json`) is stored for
	 *     debugging and fallback purposes.
	 * 3.  **Binary File:** A fast, serialized version (`user_profile.dat`) is saved using FST for
	 *     quick I/O and legacy support.
	 *
	 * The entire operation is executed on a background thread to avoid blocking the main UI thread.
	 * Any errors encountered during the process are caught and logged, preventing the app from crashing.
	 */
	fun updateInStorage() {
		ThreadsUtility.executeInBackground(
			timeOutInMilli = 100, codeBlock = {
			try {
				logger.d("Updating user profile in storage")
				saveToBinary(fileName = USER_PROFILE_FILE_NAME_BINARY)
				saveStringToInternalStorage(
					fileName = USER_PROFILE_FILE_NAME_JSON,
					data = convertClassToJSON()
				)
				AIOUserProfileDBManager.saveUserProfileInDB(userProfile = this)
				logger.d("User profile successfully updated in storage")
			} catch (error: Exception) {
				logger.e("Error updating user profile in storage: ${error.message}", error)
			}
		})
	}
	
	/**
	 * Serializes the current `AIOUserProfile` instance and saves it to a binary file
	 * in the application's private internal storage. This method uses FST (Fast-Serialization)
	 * for efficient and fast data persistence.
	 *
	 * The operation is synchronized to prevent concurrent write access. Any exceptions
	 * during the file writing process are caught and logged.
	 *
	 * @param fileName The name of the binary file (e.g., "user_profile.dat") where the
	 *                 serialized profile data will be stored.
	 */
	@Synchronized
	private fun saveToBinary(fileName: String) {
		try {
			logger.d("Saving user profile to binary file: $fileName")
			val fileOutputStream = INSTANCE.openFileOutput(fileName, MODE_PRIVATE)
			fileOutputStream.use { fos ->
				val bytes = fstConfig.asByteArray(this)
				fos.write(bytes)
				logger.d("Binary user profile saved successfully")
			}
		} catch (error: Exception) {
			logger.e("Error saving binary user profile: ${error.message}", error)
		}
	}
	
	/**
	 * Loads and deserializes the user profile from a binary file.
	 *
	 * This method reads a user profile from a binary file (`user_profile.dat`) serialized with
	 * FST (Fast-Serialization). It serves as a backward-compatibility layer to import data
	 * from the legacy binary persistence format.
	 *
	 * If the specified file does not exist, the function returns `null`.
	 *
	 * If any error occurs during file reading or deserialization (e.g., due to file corruption
	 * or a class structure mismatch), the corrupted file is deleted to prevent future load
	 * errors, and the function returns `null`.
	 *
	 * @param userProfileBinaryFile The [File] object pointing to the binary user profile.
	 * @return An `AIOUserProfile` instance if deserialization is successful; otherwise, `null`.
	 */
	private fun loadFromBinary(userProfileBinaryFile: File): AIOUserProfile? {
		if (!userProfileBinaryFile.exists()) {
			logger.d("Binary user profile file does not exist")
			return null
		}
		
		return try {
			logger.d("Loading user profile from binary file")
			val bytes = userProfileBinaryFile.readBytes()
			fstConfig.asObject(bytes).apply {
				logger.d("Successfully loaded user profile from binary file")
			} as AIOUserProfile
		} catch (error: Exception) {
			logger.e("Error loading binary user profile: ${error.message}", error)
			userProfileBinaryFile.delete()
			null
		}
	}
	
	/**
	 * Serializes the current `AIOUserProfile` instance into a JSON string.
	 *
	 * This function uses the `DslJson` library for efficient serialization. The output is a
	 * UTF-8 encoded JSON string that represents the state of this object. This is primarily
	 * used for persisting the user profile in a human-readable format for debugging
	 * and backward compatibility.
	 *
	 * @return A JSON string representation of the user profile.
	 */
	fun convertClassToJSON(): String {
		val jsonOutputStream = ByteArrayOutputStream(16 * 1024)
		logger.d("Converting user profile to JSON")
		jsonOutputStream.reset()
		aioDSLJsonInstance.serialize(this, jsonOutputStream)
		return jsonOutputStream.toString(Charsets.UTF_8.name())
	}
	
	companion object {
		
		/**
		 * A logger instance for logging events and errors related to the AIOUserProfile class,
		 * primarily used for static operations within the companion object.
		 */
		private val logger = LogHelperUtils.from(AIOUserProfile::class.java)
		
		/**
		 * Filename for the JSON representation of the user profile, stored in the app's internal storage.
		 * This file provides a human-readable backup and is used for debugging or as a fallback
		 * if other persistence methods fail.
		 */
		const val USER_PROFILE_FILE_NAME_JSON: String = "user_profile.json"
		
		/**
		 * The filename for the binary-serialized user profile data.
		 *
		 * This file stores the `AIOUserProfile` object in a fast, compact binary format using
		 * FST serialization. It is used as a legacy persistence method for quick read/write
		 * operations before migrating to or alongside the ObjectBox database.
		 *
		 * @see AIOUserProfile.saveToBinary
		 * @see AIOUserProfile.loadFromBinary
		 */
		const val USER_PROFILE_FILE_NAME_BINARY: String = "user_profile.dat"
		
		/**
		 * Deserializes a JSON string into an [AIOUserProfile] object.
		 *
		 * This function takes a JSON representation of a user profile and converts it
		 * back into an `AIOUserProfile` instance using the DSL-JSON library. If the
		 * deserialization fails or the input string is empty/invalid, it returns a
		 * new, empty `AIOUserProfile` object to prevent null pointer exceptions.
		 *
		 * @param jsonString The JSON string to be deserialized.
		 * @return An [AIOUserProfile] object populated with data from the JSON string,
		 *         or a default `AIOUserProfile` instance if deserialization fails.
		 */
		@JvmStatic
		fun convertJSONStringToClass(jsonString: String): AIOUserProfile {
			logger.d("Converting JSON to user profile object")
			val inputStream = ByteArrayInputStream(jsonString.encodeToByteArray())
			val loadedUserProfile: AIOUserProfile = aioDSLJsonInstance
				.deserialize(AIOUserProfile::class.java, inputStream) ?: AIOUserProfile()
			return loadedUserProfile
		}
	}
}