package app.core.engines.youtube

import com.dslplatform.json.*
import io.objectbox.annotation.*
import lib.process.*
import java.io.*

/**
 * Data model representing a YouTube video with its metadata and available formats.
 * This entity is persisted in the local database using ObjectBox and supports JSON serialization.
 *
 * @property id Unique database identifier (auto-generated by ObjectBox)
 * @property videoUrl The complete URL of the YouTube video
 * @property videoTitle Title of the YouTube video
 * @property videoThumbnailUrl URL to the video's thumbnail image
 * @property videoDescription Video description text
 * @property videoDuration Formatted duration string (e.g., "10:30")
 * @property videoViewsCount Formatted view count string (e.g., "1.5M views")
 * @property videoLikesCount Formatted like count string
 * @property videoChannelName Name of the YouTube channel
 * @property videoFormats List of available video/audio formats for download
 */
@CompiledJson
@Entity
class YouTubeVideoDataModel(
	@Id
	@JvmField
	@param:JsonAttribute(name = "id")
	var id: Long = 0L,
	
	@JvmField
	@param:JsonAttribute(name = "videoUrl")
	var videoUrl: String = "",
	
	@JvmField
	@param:JsonAttribute(name = "videoTitle")
	var videoTitle: String? = null,
	
	@JvmField
	@param:JsonAttribute(name = "videoThumbnailUrl")
	var videoThumbnailUrl: String? = null,
	
	@JvmField
	@param:JsonAttribute(name = "videoDescription")
	var videoDescription: String? = null,
	
	@JvmField
	@param:JsonAttribute(name = "videoDuration")
	var videoDuration: String? = null,
	
	@JvmField
	@param:JsonAttribute(name = "videoViewsCount")
	var videoViewsCount: String? = null,
	
	@JvmField
	@param:JsonAttribute(name = "videoLikesCount")
	var videoLikesCount: String? = null,
	
	@JvmField
	@param:JsonAttribute(name = "videoChannelName")
	var videoChannelName: String? = null,
) : Serializable {
	
	// Logger for tracking operations on this model instance
	private val logger = LogHelperUtils.from(javaClass)
	
	/**
	 * Persists this video model to the local database asynchronously.
	 * The operation runs in background with a 500ms timeout.
	 *
	 * @see YTVideosModelsDBManager.saveYouTubeVideoDataModelInDB
	 * @see ThreadsUtility.executeInBackground
	 */
	fun updateInStorage() {
		ThreadsUtility.executeInBackground(
			timeOutInMilli = 500,
			codeBlock = {
				YTVideosModelsDBManager.saveYouTubeVideoDataModelInDB(
					this, object : YTVideosModelsDBManager.OnSaveResultListener {
					override fun onSuccess(savedId: Long) {
						logger.d("YouTube video model saved to storage successfully.")
					}
					
					override fun onError(error: Exception) {
						logger.d("Failed to save YouTube video model to storage.")
					}
				}
				)
			}
		)
	}
	
	/**
	 * Removes this video model from the local database asynchronously.
	 * Uses the model's ID to locate and delete the record with 500ms timeout.
	 *
	 * @see YTVideosModelsDBManager.deleteYouTubeVideoById
	 * @see ThreadsUtility.executeInBackground
	 */
	fun clearFromStorage() {
		ThreadsUtility.executeInBackground(
			timeOutInMilli = 500,
			codeBlock = {
				val isDeleted = YTVideosModelsDBManager.deleteYouTubeVideoById(id)
				logger.d(
					"Deletion of YouTube video model from storage was " +
						"${if (isDeleted) "successful" else "failed"}."
				)
			}
		)
	}
}