package app.core.engines.browser

import io.objectbox.annotation.*
import java.io.*
import java.util.*

/**
 * Represents a web record entity that stores information about web pages,
 * bookmarks, and browsing history entries.
 *
 * This data class serves as the primary model for managing web-related records
 * in the browser engine. It supports ObjectBox database persistence and
 * JSON serialization/deserialization via Gson annotations.
 *
 * @property id Unique identifier for the record (auto-generated by ObjectBox)
 * @property url The complete URL of the web resource
 * @property name Display name or title of the web page
 * @property creationDate Timestamp when the record was created
 * @property modifiedDate Timestamp when the record was last modified
 * @property thumbFilePath File system path to the thumbnail image
 * @property description Text description or summary of the web page
 * @property tags List of categorization tags for filtering and searching
 * @property favorite Flag indicating if this is a favorite/bookmarked page
 * @property folder Virtual folder path for organizing records
 * @property isBookmark Flag distinguishing bookmarks from history entries
 * @property accessCount Number of times this record has been accessed
 * @property lastAccessed Timestamp of the most recent access
 *
 * @see Serializable For object serialization support
 * @see Entity ObjectBox database entity annotation
 */
@Entity
data class AIOWebRecords(

	/**
	 * Unique identifier for the database record.
	 *
	 * Annotated with @Id for ObjectBox auto-incrementing primary key.
	 * Default value 0 indicates a new (unsaved) entity.
	 *
	 * @see Id ObjectBox primary key annotation
	 */
	@Id
	var id: Long = 0,

	/**
	 * Complete URL of the web resource.
	 *
	 * Should include protocol (http:// or https://) and may include
	 * path, query parameters, and fragment identifiers.
	 *
	 * Example: "https://example.com/page?param=value#section"
	 */
	@Index(type = IndexType.HASH)
	var url: String = "",

	/**
	 * Display name or title of the web page.
	 *
	 * Typically extracted from the HTML &lt;title&gt; tag or
	 * user-provided for custom bookmarks.
	 */
	@Index
	var name: String = "",

	/**
	 * Timestamp when this record was initially created.
	 *
	 * Automatically set to current date/time upon record creation.
	 * Used for sorting by recency and historical analysis.
	 */
	@Index
	var creationDate: Date = Date(),

	/**
	 * Timestamp when this record was last modified.
	 *
	 * Updates when any field (name, description, tags, etc.) is changed.
	 * Used for synchronization and change tracking.
	 */
	var modifiedDate: Date = Date(),

	/**
	 * File system path to the thumbnail image for this web page.
	 *
	 * Stores location of generated screenshot or preview image.
	 * Path can be absolute or relative to application storage.
	 */
	var thumbFilePath: String = "",

	/**
	 * Text description or summary of the web page.
	 *
	 * Can be auto-extracted from meta description tags or
	 * manually entered by the user for annotation.
	 */
	var description: String = "",

	/**
	 * List of categorization tags for filtering and searching.
	 *
	 * Enables faceted search and organization by topic.
	 * Example: ["news", "technology", "tutorial"]
	 */
	var tags: String = "",

	/**
	 * Flag indicating if this record is marked as favorite.
	 *
	 * Favorites receive special highlighting and are typically
	 * displayed in a dedicated "Favorites" section.
	 */
	@Index
	var favorite: Boolean = false,

	/**
	 * Virtual folder path for hierarchical organization.
	 *
	 * Uses forward-slash separated paths like "Work/Projects/Current"
	 * for nested folder structures.
	 */
	@Index
	var folder: String = "",

	/**
	 * Flag distinguishing bookmarks from history entries.
	 *
	 * True for user-saved bookmarks, false for automatic history entries.
	 * Affects retention policies and UI display.
	 */
	@Index
	var isBookmark: Boolean = false,

	/**
	 * Number of times this web page has been accessed.
	 *
	 * Incremented each time the user navigates to this URL.
	 * Used for popularity ranking and usage analytics.
	 */
	@Index
	var accessCount: Int = 0,

	/**
	 * Timestamp of the most recent access to this web page.
	 *
	 * Updated every time the user visits the URL.
	 * Useful for "Recently Visited" features and cleanup policies.
	 */
	@Index
	var lastAccessed: Date = Date()

) : Serializable